py_binary(
    name = "generate_training",
    srcs = ["generate_training.py"],
    data = ["//utils:w2v.so"],
    imports = ["../../utils"],
)

py_binary(
    name = "process_icwb",
    srcs = ["process_icwb.py"],
    data = ["//utils:w2v.so"],
    imports = ["../../utils"],
)

py_binary(
    name = "process_people",
    srcs = ["process_people.py"],
    data = ["//utils:w2v.so"],
    imports = ["../../utils"],
)

py_binary(
    name = "generate_char_embedding",
    srcs = ["generate_char_embedding.py"],
    data = ["//utils:w2v.so"],
    imports = ["../../utils"],
)

py_binary(
    name = "generate_pos_train",
    srcs = ["generate_pos_train.py"],
    data=['//utils:w2v.so'],
    imports=['../../utils']
)

py_binary(
    name = "generate_training_VideoTitle",
    srcs = ["generate_training_VideoTitle.py"],
    data = ["//utils:w2v.so"],
    imports = ["../../utils"],
)

py_binary(
    name = "generate_training_ICWB",
    srcs = ["generate_training_ICWB.py"],
    data = ["//utils:w2v.so"],
    imports = ["../../utils"],
)

py_binary(
    name = "generate_pos_VideoTitle_test",
    srcs = ["generate_pos_VideoTitle_test.py"],
    data = ["//utils:w2v.so"],
    imports = ["../../utils"],
)
